import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { AgentCore } from "./agentCore.js"; // 导入 AgentCore

// 定义 ContextProxy 类
export class ContextProxy {
  private mcpServer: McpServer;
  private agentCore: AgentCore; // 添加 agentCore 实例

  constructor(mcpServer: McpServer, agentCore: AgentCore) { // 构造函数接收 AgentCore
    this.mcpServer = mcpServer;
    this.agentCore = agentCore;
  }

  /**
   * 拦截并处理发送给 AI 提供商的请求。
   * @param clientRequest AI 客户端的原始请求。
   * @param aiProviderCall 用于实际调用 AI 提供商的函数。
   * @returns AI 提供商的原始响应。
   */
  async processRequest(
    clientRequest: string,
    aiProviderCall: (injectedRequest: string) => Promise<string>
  ): Promise<string> {
    let parsedRequest: any;
    try {
      parsedRequest = JSON.parse(clientRequest);
    } catch (error) {
      console.error("Failed to parse clientRequest as JSON:", error);
      // If not JSON, treat as plain text and proceed without context management
      const injectedRequest = `${clientRequest} 请检查话题内容是否已经切换，若为新话题则卸载无关上下文`;
      console.log(`Injected Request to AI Provider (plain text): "${injectedRequest}"`);
      return await aiProviderCall(injectedRequest);
    }

    const messages = parsedRequest.messages;
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      console.warn("No messages found in clientRequest. Proceeding without context management.");
      return await aiProviderCall(clientRequest);
    }

    const lastUserMessage = messages[messages.length - 1];
    const oldContextMessages = messages.slice(0, messages.length - 1);

    // const offloadingManager = this.agentCore.getOffloadingManager();
    // const contextManager = this.agentCore.getContextManager();
    const injectedPromptTemplate = this.agentCore.getInjectedPromptTemplate();

    const currentContextContent = JSON.stringify(oldContextMessages);
    const finalMessages = [...oldContextMessages];
    const injectedPrompt =
      typeof injectedPromptTemplate === "string" && injectedPromptTemplate.length > 0
        ? ` ${injectedPromptTemplate}`
        : "";

    finalMessages.push(lastUserMessage);

    // 将注入的提示添加到最后一条用户消息中
    finalMessages[finalMessages.length - 1].content += injectedPrompt;

    // Construct the request with potentially modified messages
    const injectedRequestObject = { ...parsedRequest, messages: finalMessages };
    const injectedRequest = JSON.stringify(injectedRequestObject);

    console.log(`Injected Request to AI Provider: "${injectedRequest}"`);

    let aiResponse: string;
    try {
      aiResponse = await aiProviderCall(injectedRequest);
    } catch (error: any) {
      // 增加一条：如果提供商返回429、500等错误，同时上下文长度确实很长，那么应该进行卸载
      if ((error.response && (error.response.status === 429 || error.response.status === 500)) && currentContextContent.length > 2000) { // Arbitrary length for "very long"
        console.warn("AI Provider returned error (429/500) and context is long. Attempting to offload context and retry.");
        try {
          // 自动卸载上下文内容，使用默认摘要和关键词
          const autoGeneratedSummary = `Auto-offloaded context due to provider error (length: ${currentContextContent.length})`;
          const autoGeneratedKeywords: string[] = ["auto-offloaded", "context-error"];

          const offloadResult = await this.agentCore.getOffloadingManager().offloadContent(currentContextContent, undefined, autoGeneratedSummary, autoGeneratedKeywords);
          console.log(`Auto-offload result after error: ${offloadResult.id}`);
          const summaryMessage = {
            role: "system",
            content: `Previous conversation context was too long and has been auto-offloaded due to AI provider error. Reference ID: ${offloadResult.id}`,
          };
          const retryMessages = [summaryMessage, lastUserMessage];
          const retryRequestObject = { ...parsedRequest, messages: retryMessages };
          const retryRequest = JSON.stringify(retryRequestObject);
          aiResponse = await aiProviderCall(retryRequest); // Retry with reduced context
        } catch (offloadError) {
          console.error("Failed to auto-offload content after AI provider error:", offloadError);
          throw error; // Re-throw original error if offloading/retry fails
        }
      } else {
        throw error; // Re-throw other errors
      }
    }

    console.log(`AI Provider Raw Response: "${aiResponse}"`);

    // 保存当前请求内容，以便下次检测主题变更 (此逻辑也应由 AI 决定，或在工具调用后处理)
    // await contextManager.saveContext("last_request_content", lastUserMessage.content); // Save only the last user message for topic detection

    // 直接返回 AI 提供商的原始响应，由 AI 客户端自行处理工具调用
    return aiResponse;
  }

  /**
   * 处理 AI 客户端执行工具调用后的结果，进行上下文替换和响应重构。
   * @param originalAIResponse AI 提供商的原始响应，其中可能包含工具调用建议。
   * @param toolCallResult AI 客户端执行工具调用后返回的结果。
   * @returns 经过上下文替换和响应重构后的最终响应。
   */
  async handleToolCallResult(
    originalAIResponse: string,
    toolCallResult: any
  ): Promise<string> {
    // 假设工具调用结果是 offloadContent 的结果
    const offloadedSegmentId = toolCallResult.offloadedSegmentId;
    const status = toolCallResult.status;
    const message = toolCallResult.message;

    // 5. 上下文替换和请求重构 (简化示例)
    let finalResponseToClient = originalAIResponse;

    // 假设原始响应中包含工具调用的占位符或特定格式，需要被替换
    // 这里我们只是简单地在原始响应前添加上下文更新信息
    if (status === "success") {
      finalResponseToClient = `Context Offloaded (ID: ${offloadedSegmentId}, Status: ${status}). ${message}\n${originalAIResponse}`;
    } else {
      finalResponseToClient = `Context Offload Failed (Status: ${status}). ${message}\n${originalAIResponse}`;
    }

    return finalResponseToClient;
  }
}